import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Footer } from "@/components/elements/Footer";
import { AppProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>onigiri.w2</title>
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </head>
      <body
        className={`${inter.className} mx-auto flex min-h-screen max-w-3xl flex-col dark:bg-dark-800`}
        suppressHydrationWarning={true}
      >
        <AppProvider>
          <main className="grow">{children}</main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
